version: '3'
services:
  app:
    build: ./
    restart: always
    container_name: tg-game_front
    ports:
      - "127.0.0.1:8085:80"

  bot:
    build: ./bot
    restart: always
    container_name: tg-game_bot
    env_file:
      - .env

  db:
    restart: always
    image: postgres:15.3-alpine
    container_name: tg-game_db
    env_file:
      - .env
    ports:
      - "5432:5432"
